# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0002_restuarants_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restuarants',
            new_name='RestuarantLocation',
        ),
    ]
