# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0003_auto_20180715_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
