# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0004_restuarantlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
